In [1]:
import numpy as np
import sys
import time

In [2]:
arr= np.array([1,23,45,6455,64,5])
print(arr)

[   1   23   45 6455   64    5]


In [3]:
type(arr)

numpy.ndarray

In [4]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [5]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
type(arr1)

numpy.ndarray

In [43]:
arr = np.array([[[1,23,4],[1,54,6]],[[1,23,5],[8,5,96]]])

In [44]:
arr*2

array([[[  2,  46,   8],
        [  2, 108,  12]],

       [[  2,  46,  10],
        [ 16,  10, 192]]])

In [10]:
arr = np.zeros(5)

In [11]:
arr

array([0., 0., 0., 0., 0.])

In [14]:
arr = np.zeros((2,3))

In [15]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr = np.ones(5)

In [17]:
arr

array([1., 1., 1., 1., 1.])

In [18]:
type(arr)

numpy.ndarray

In [19]:
arr = np.empty(6)

In [20]:
arr

array([0., 0., 0., 0., 0., 0.])

In [21]:
arr = np.empty((2,3))

In [22]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
arr = np.full((3,4),7)

In [24]:
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [25]:
arr = np.arange(0,25,3)

In [26]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [29]:
arr = np.linspace(0,2,10)

In [30]:
arr


array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [31]:
arr = np.random.randint(0,15,size = (3,3))

In [32]:
arr

array([[11, 10,  6],
       [11, 10,  1],
       [ 9, 10,  4]])

In [33]:
arr = np.random.randint(0,10,6)

In [34]:
arr

array([0, 4, 5, 3, 3, 5])

In [37]:
arr = np.random.random((2,3))

In [38]:
arr

array([[0.99668693, 0.79690162, 0.60487652],
       [0.84567437, 0.06986573, 0.69344084]])

In [40]:
arr = np.random.randn(2,3)

In [41]:
arr

array([[ 0.59916571,  1.673448  ,  1.04301944],
       [-1.74081385, -0.85458706,  2.05752643]])

In [51]:
arr = np.arange(0,10,2)
print(arr)
np.sum(arr)

[0 2 4 6 8]


20

In [46]:
np.std(arr)

2.8284271247461903

In [47]:
np.mean(arr)

4.0

In [48]:
np.min(arr)

0

In [49]:
np.max(arr)

8

In [50]:
np.sqrt(arr)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712])

In [3]:
arr = np.array([])

In [4]:
arr

array([], dtype=float64)

In [5]:
li = []

In [6]:
sys.getsizeof(arr)

112

In [7]:
sys.getsizeof(li)

56

In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
li = [1,2,3,4,5,6,7,8,9,10]

In [12]:
sys.getsizeof(arr)

152

In [13]:
sys.getsizeof(li)

136

In [3]:
list_1 = [i for i in range(10000000)]
list_2 = [i for i in range(10000000)]
list_3 = [0 for i in range(10000000)]
start = time.time()
for i in range(len(list_1)):
    list_3[i] = list_1[i] + list_2[i]
end  = time.time()

total = end - start

print(total)

3.0153727531433105


In [4]:
arr_1 = np.array(list_1)
arr_2 = np.array(list_2)
start = time.time()
arr_3 = arr_1 + arr_2
end = time.time()
total = end - start

print(total)

0.021388530731201172


In [6]:
arr = np.array([1,24,56,5485,1,21,34])
arr[30<arr]

array([  56, 5485,   34])

In [10]:
arr = np.arange(1,80,2)
arr.shape

(40,)

In [11]:
arr = np.random.randint(1,30,36)

In [13]:
arr.shape

(36,)

In [18]:
np.reshape(arr,(6,6))

array([[ 4, 15, 21,  8, 17, 13],
       [27, 17, 25, 25, 10, 28],
       [ 1,  4, 24, 29, 13,  5],
       [ 4,  6,  5,  7, 17, 14],
       [16, 18,  4, 10, 22, 15],
       [23,  4, 17, 19, 20,  8]])

In [19]:
np.reshape(arr,(9,4))

array([[ 4, 15, 21,  8],
       [17, 13, 27, 17],
       [25, 25, 10, 28],
       [ 1,  4, 24, 29],
       [13,  5,  4,  6],
       [ 5,  7, 17, 14],
       [16, 18,  4, 10],
       [22, 15, 23,  4],
       [17, 19, 20,  8]])

In [20]:
arr_1 = np.array([1,2,3])
np.transpose(arr_1)

array([1, 2, 3])

In [21]:
arr_2 = np.array([[1,2,3],[5,4,6]])
np.transpose(arr_2)

array([[1, 5],
       [2, 4],
       [3, 6]])